## Tells the LMS should output raw measurements to "/sick/scan"
bool EnableRawOutput

## Which filter to select
##   0 = None
##   1 = Averaging
##   2 = Median filter
int8 FilterSelect

## Is the SICK scanner upside down?
bool UpsideDown
---
