/* Auto-generated by genmsg_cpp for file /home/daniel/fieldrobot_workspace/Flarb/flarb_inclination/msg/inclination.msg */
#ifndef FLARB_INCLINATION_MESSAGE_INCLINATION_H
#define FLARB_INCLINATION_MESSAGE_INCLINATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace flarb_inclination
{
template <class ContainerAllocator>
struct inclination_ {
  typedef inclination_<ContainerAllocator> Type;

  inclination_()
  : x(0.0)
  , y(0.0)
  {
  }

  inclination_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;


  typedef boost::shared_ptr< ::flarb_inclination::inclination_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flarb_inclination::inclination_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct inclination
typedef  ::flarb_inclination::inclination_<std::allocator<void> > inclination;

typedef boost::shared_ptr< ::flarb_inclination::inclination> inclinationPtr;
typedef boost::shared_ptr< ::flarb_inclination::inclination const> inclinationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::flarb_inclination::inclination_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::flarb_inclination::inclination_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace flarb_inclination

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::flarb_inclination::inclination_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::flarb_inclination::inclination_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::flarb_inclination::inclination_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const  ::flarb_inclination::inclination_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::flarb_inclination::inclination_<ContainerAllocator> > {
  static const char* value() 
  {
    return "flarb_inclination/inclination";
  }

  static const char* value(const  ::flarb_inclination::inclination_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::flarb_inclination::inclination_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#X Axis in Float\n\
float32 x\n\
#Y Axis in Float\n\
float32 y\n\
\n\
";
  }

  static const char* value(const  ::flarb_inclination::inclination_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::flarb_inclination::inclination_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::flarb_inclination::inclination_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct inclination_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flarb_inclination::inclination_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::flarb_inclination::inclination_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FLARB_INCLINATION_MESSAGE_INCLINATION_H

